a=10
b=2 
print("addition of a and b is",a+b)
print("multiplication of a and b is",a*b)
print("subtraction of a and b is",a-b)
print("division of a and b is",a/b)
print("floor division of a and b is",a//b)
print("modelus of a and b is", a%b)
print("square of a and is",a**a)
print("square of b and is",b**b) 
print("squareroot of a is",a**0.5)
print("squareroot of b is",b**0.5)
print("equal or not?",a==b)
print("number 1 greater?",a>b)
print("number 2 greater?",b>a)

